# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge"
