name: goreleaser
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - name: fetch tags
        run: git fetch --tags --force

      - uses: actions/setup-go@v6.5.0
        with:
          go-version: "1.26"

      - uses: goreleaser/goreleaser-action@v7.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release -f ci/.goreleaser.yml
